
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 89
#define YY_END_OF_BUFFER 90
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[327] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       90,   71,    1,   71,   42,   42,   72,    3,   72,   72,
       72,   76,    7,   76,   76,   76,   76,   77,    8,   77,
       45,   78,    9,   78,   46,   47,   73,    4,   73,   73,
       73,   73,   73,   73,   73,   73,   89,   79,   79,   79,
       58,   81,   11,   81,   81,   80,   10,   80,   80,   63,
       74,    5,   74,   51,   75,    6,   75,   52,   53,   82,

        2,   69,   82,   65,   83,   12,   66,   83,   84,   14,
       67,   84,   85,   13,   85,   85,   86,   15,   86,   55,
       87,   16,   87,   39,   88,   17,   88,   40,   41,    1,
        0,   42,   42,    3,    0,    0,    0,    7,    0,   48,
        0,    0,    8,    0,    9,    0,    4,    0,   70,   64,
        0,    0,    0,    0,    0,    0,   57,   11,    0,   60,
       10,    0,   62,    5,    0,    6,    0,    2,    0,   65,
       12,   66,    0,   14,   67,    0,   13,    0,   68,   15,
        0,   16,    0,   39,   17,    0,    0,    0,   42,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   18,   42,   20,    0,    0,   24,    0,    0,
       25,   26,   21,    0,    0,    0,    0,    0,    0,   27,
       29,   28,   23,   22,   19,   30,   32,   31,   33,   34,
       35,   42,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   42,    0,    0,    0,    0,    0,    0,    0,
        0,   56,    0,   42,   43,    0,    0,    0,    0,    0,
        0,    0,    0,   36,    0,   44,   37,   50,    0,    0,

        0,   38,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   61,    0,    0,    0,   59,
        0,    0,   54,    0,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    3,    4,    1,    1,
        5,    6,    1,    1,    1,    7,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,   10,    1,
        1,    1,    1,    1,   11,   12,   12,   13,   12,   12,
       14,   12,   12,   12,   12,   12,   12,   12,   12,   15,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       16,   16,   16,   16,   17,   16,   18,   19,   20,   12,

       21,   22,   12,   23,   24,   12,   25,   26,   27,   28,
       29,   30,   12,   31,   32,   33,   34,   35,   36,   12,
       12,   12,   37,    1,   38,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[39] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    4,    1,
        4,    4,    4,    4,    4,    5,    6,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1
    } ;

static const flex_int16_t yy_base[367] =
    {   0,
        0,   38,    6,    8,   16,   44,   22,   24,   79,  117,
      155,    0,    0,    0,  193,  231,  269,  307,  345,  383,
       28,   55,  421,  459,  497,  535,    0,    0,  573,  611,
      649,  687,  725,  763,   47,   61,  801,  839,  877,  915,
      491, 1177,    0,  484,    0,  471, 1177,    0,  482,  456,
      452, 1177,    0,  479,  474,  457,  464, 1177,    0,  475,
     1177, 1177,    0,  474, 1177, 1177, 1177,    0,  473,  468,
      468,    3,    4,   40,   44,   79, 1177, 1177,  468,  464,
     1177, 1177,    0,  466,  462, 1177,    0,  464,  459, 1177,
     1177,    0,  451, 1177, 1177,    0,  450, 1177, 1177, 1177,

        0, 1177,  449,    0, 1177,    0,    0,  448, 1177,    0,
        0,  447, 1177,    0,  446,  442, 1177,    0,  444, 1177,
     1177,    0,  443,    0, 1177,    0,  442, 1177, 1177,    0,
       92,    0,  416,    0,   98,  428,  413,    0,  100, 1177,
      414,  412,    0,  106,    0,  108,    0,  124, 1177,  433,
      411,  412,  415,  418,  404,  130,  425,    0,  133,  424,
        0,  136,  423,    0,  139,    0,  142,    0,  145,    0,
        0,    0,  205,    0,    0,  211,    0,  213,  421,    0,
      219,    0,  221,    0,    0,  243,  249,  411,  394,  251,
      409,  389,  392,  257,  406,  390,  388,  259,  403,  281,

      402,  287,  401,  385,  389,  373,   58,  381,  289,  396,
      295,  395,  297,  394,  319,  393,  325,  390,  327,  389,
      333,  388,  335,  387,  357,  386,  363,  373,  365,  372,
      371,  371, 1177,  358, 1177,  348,  361, 1177,  350,  348,
     1177, 1177, 1177,  342,  332,  333,  331,  322,  320, 1177,
     1177, 1177, 1177, 1177, 1177, 1177, 1177, 1177, 1177, 1177,
     1177,  317,  312,  299,  303,  301,  300,  301,  287,  283,
      266,  273,  264,  253,  246,  260,  254,  246,  230,  234,
      236, 1177,  226,  225, 1177,  216,  210,  221,  196,  191,
      205,  190,  193,    0,  197, 1177, 1177, 1177,  188,  173,

      174, 1177,  119,  117,   96,  105,   78,   88,   85,   83,
       64,   58,   41,   53,   43, 1177,   46,   45,   42, 1177,
       23,    0, 1177,    0, 1177, 1177,  953,  959,  965,  971,
      977,  983,  989,  995, 1001, 1007, 1013, 1019, 1025, 1031,
     1037, 1043, 1049, 1055, 1061, 1064, 1070, 1076, 1082, 1088,
     1094, 1100, 1106, 1112, 1118, 1124, 1127, 1133, 1137, 1141,
     1145, 1149, 1155, 1161, 1164, 1170
    } ;

static const flex_int16_t yy_def[367] =
    {   0,
      327,  327,  328,  328,  329,  329,  330,  330,  331,  331,
      326,   11,  332,  332,  333,  333,  334,  334,  335,  335,
      336,  336,  337,  337,  338,  338,  332,  332,  339,  339,
      340,  340,  341,  341,  342,  342,  343,  343,  344,  344,
      326,  326,  345,  326,  346,  346,  326,  347,  326,  326,
      326,  326,  348,  326,  326,  326,  326,  326,  349,  326,
      326,  326,  350,  326,  326,  326,  326,  351,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  352,  326,  326,  326,  353,  326,  326,  326,
      326,  354,  326,  326,  326,  355,  326,  326,  326,  326,

      356,  326,  326,  357,  326,  358,  359,  326,  326,  360,
      361,  326,  326,  362,  326,  326,  326,  363,  326,  326,
      326,  364,  326,  365,  326,  366,  326,  326,  326,  345,
      326,  346,  346,  347,  326,  326,  326,  348,  326,  326,
      326,  326,  349,  326,  350,  326,  351,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  352,  326,  326,
      353,  326,  326,  354,  326,  355,  326,  356,  326,  357,
      358,  359,  326,  360,  361,  326,  362,  326,  326,  363,
      326,  364,  326,  365,  366,  326,  326,  326,  346,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  346,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  346,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  346,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  346,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  346,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,    0,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326
    } ;

static const flex_int16_t yy_nxt[1216] =
    {   0,
       42,   42,   43,   42,   42,   42,   42,   44,   48,   42,
       48,  150,  150,   49,  326,   49,  326,  325,   53,   50,
       51,   50,   51,   54,   59,   55,   59,  152,  151,   60,
       92,   60,  324,   56,   46,   93,   42,   42,   42,   42,
       43,   42,   42,   42,   42,   44,   53,   42,  150,  118,
       57,   54,  150,   55,  119,  323,  120,   92,   61,  322,
       61,   56,   93,  118,   94,  321,  320,  153,  119,  319,
      120,  318,   46,  317,   42,   42,  154,  247,   57,   62,
       62,   63,   62,   62,   62,   62,   64,  150,   62,  316,
      248,   94,  315,  187,   62,   62,  155,  188,  187,  190,

      314,  194,  313,  191,  190,  195,  194,  198,  312,  200,
      311,  199,  198,  201,  200,   62,   66,   62,   62,   63,
       62,   62,   62,   62,   64,  202,   62,  310,  309,  203,
      202,  209,   62,   62,  211,  210,  209,  213,  212,  211,
      215,  214,  213,  217,  216,  215,  219,  218,  217,  308,
      220,  219,  307,   62,   66,   67,   67,   68,   67,   67,
       67,   67,   69,   67,   70,   71,   71,   71,   71,   71,
       67,   67,   72,   71,   71,   71,   73,   71,   74,   71,
       71,   71,   71,   71,   71,   71,   75,   71,   71,   76,
       71,   67,   67,   78,   78,   78,   78,   78,   78,   78,

       79,   78,   78,  306,  305,  304,  221,  303,   78,   78,
      222,  221,  223,  302,  225,  301,  224,  223,  226,  225,
      227,  300,  229,  299,  228,  227,  230,  229,  298,   78,
       81,   78,   78,   78,   78,   78,   78,   78,   79,   78,
       78,  297,  296,  295,  231,  294,   78,   78,  232,  231,
      187,  293,  190,  292,  188,  187,  191,  190,  194,  291,
      198,  290,  195,  194,  199,  198,  289,   78,   81,   82,
       82,   83,   82,   82,   82,   82,   84,   82,   82,  288,
      287,  286,  200,  285,   82,   82,  201,  200,  202,  284,
      209,  283,  203,  202,  210,  209,  211,  282,  213,  281,

      212,  211,  214,  213,  280,   82,   82,   82,   82,   83,
       82,   82,   82,   82,   84,   82,   82,  279,  278,  277,
      215,  276,   82,   82,  216,  215,  217,  275,  219,  274,
      218,  217,  220,  219,  221,  273,  223,  272,  222,  221,
      224,  223,  271,   82,   82,   86,   86,   87,   86,   86,
       86,   86,   88,   86,   86,  270,  269,  268,  225,  267,
       86,   86,  226,  225,  227,  266,  229,  265,  228,  227,
      230,  229,  231,  264,  263,  262,  232,  231,  261,  260,
      259,   86,   90,   86,   86,   87,   86,   86,   86,   86,
       88,   86,   86,  258,  257,  256,  255,  254,   86,   86,

      253,  252,  251,  250,  249,  246,  245,  244,  243,  242,
      241,  240,  239,  238,  237,  236,  235,  234,  233,   86,
       90,   95,   95,   96,   95,   95,   95,   95,   97,  179,
       95,  163,  160,  157,  208,  207,   95,   95,  206,  205,
      204,  150,  197,  196,  193,  192,  189,  186,  183,  181,
      179,  178,  176,  173,  169,  167,  165,   95,   99,   95,
       95,   96,   95,   95,   95,   95,   97,  163,   95,  162,
      160,  159,  157,  156,   95,   95,  150,  149,  148,  146,
      144,  142,  141,  140,  139,  137,  136,  135,  133,  131,
      326,  326,  326,  326,  326,   95,   99,  100,  100,  101,

      100,  102,  100,  100,  103,  326,  100,  326,  326,  326,
      326,  326,  100,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  100,  100,  100,  100,  101,  100,  102,
      100,  100,  103,  326,  100,  326,  326,  326,  326,  326,
      100,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  100,  100,  105,  105,  106,  326,  105,  105,  105,
      108,  326,  105,  326,  326,  326,  326,  326,  105,  105,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  105,
      105,  105,  105,  106,  326,  105,  105,  105,  108,  326,
      105,  326,  326,  326,  326,  326,  105,  105,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  105,  105,  109,
      109,  110,  326,  109,  109,  109,  112,  326,  109,  326,
      326,  326,  326,  326,  109,  109,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  109,  109,  109,  109,  110,
      326,  109,  109,  109,  112,  326,  109,  326,  326,  326,

      326,  326,  109,  109,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  109,  109,  113,  113,  114,  113,  113,
      113,  113,  115,  113,  113,  326,  326,  326,  326,  326,
      113,  113,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  113,  113,  113,  113,  114,  113,  113,  113,  113,
      115,  113,  113,  326,  326,  326,  326,  326,  113,  113,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  113,

      113,  121,  121,  122,  121,  121,  121,  121,  123,  326,
      121,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  121,  121,  121,
      121,  122,  121,  121,  121,  121,  123,  326,  121,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  121,  121,  125,  125,  126,
      125,  125,  125,  125,  127,  326,  125,  326,  326,  326,
      326,  326,  125,  125,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  125,  129,  125,  125,  126,  125,  125,
      125,  125,  127,  326,  125,  326,  326,  326,  326,  326,
      125,  125,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  125,  129,   45,   45,   45,   45,   45,   45,   47,
       47,   47,   47,   47,   47,   52,   52,   52,   52,   52,
       52,   58,   58,   58,   58,   58,   58,   65,   65,   65,
       65,   65,   65,   77,   77,   77,   77,   77,   77,   80,
       80,   80,   80,   80,   80,   85,   85,   85,   85,   85,

       85,   89,   89,   89,   89,   89,   89,   91,   91,   91,
       91,   91,   91,   98,   98,   98,   98,   98,   98,  104,
      104,  104,  104,  104,  104,  107,  107,  107,  107,  107,
      107,  111,  111,  111,  111,  111,  111,  116,  116,  116,
      116,  116,  116,  117,  117,  117,  117,  117,  117,  124,
      124,  124,  124,  124,  124,  128,  128,  128,  128,  128,
      128,  130,  326,  130,  130,  130,  130,  132,  132,  132,
      134,  326,  134,  134,  134,  134,  138,  326,  138,  138,
      138,  138,  143,  326,  143,  143,  143,  143,  145,  326,
      145,  145,  145,  145,  147,  326,  147,  147,  147,  147,

      158,  326,  158,  158,  158,  158,  161,  326,  161,  161,
      161,  161,  164,  326,  164,  164,  164,  164,  166,  326,
      166,  166,  166,  166,  168,  326,  168,  168,  168,  168,
      170,  326,  170,  171,  326,  171,  171,  171,  171,  172,
      172,  174,  326,  174,  174,  174,  174,  175,  175,  177,
      326,  177,  177,  177,  177,  180,  326,  180,  180,  180,
      180,  182,  326,  182,  182,  182,  182,  184,  184,  184,
      185,  326,  185,  185,  185,  185,   41,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326
    } ;

static const flex_int16_t yy_chk[1216] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    1,
        4,   72,   73,    3,    0,    4,    0,  324,    5,    3,
        3,    4,    4,    5,    7,    5,    8,   73,   72,    7,
       21,    8,  322,    5,    1,   21,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    6,    2,   74,   35,
        5,    6,   75,    6,   35,  321,   35,   22,    7,  319,
        8,    6,   22,   36,   21,  318,  317,   74,   36,  315,
       36,  314,    2,  313,    2,    2,   75,  207,    6,    9,
        9,    9,    9,    9,    9,    9,    9,   76,    9,  312,
      207,   22,  311,  131,    9,    9,   76,  131,  131,  135,

      310,  139,  309,  135,  135,  139,  139,  144,  308,  146,
      307,  144,  144,  146,  146,    9,    9,   10,   10,   10,
       10,   10,   10,   10,   10,  148,   10,  306,  305,  148,
      148,  156,   10,   10,  159,  156,  156,  162,  159,  159,
      165,  162,  162,  167,  165,  165,  169,  167,  167,  304,
      169,  169,  303,   10,   10,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   15,   15,   15,   15,   15,   15,   15,

       15,   15,   15,  301,  300,  299,  173,  295,   15,   15,
      173,  173,  176,  293,  178,  292,  176,  176,  178,  178,
      181,  291,  183,  290,  181,  181,  183,  183,  289,   15,
       15,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,  288,  287,  286,  186,  284,   16,   16,  186,  186,
      187,  283,  190,  281,  187,  187,  190,  190,  194,  280,
      198,  279,  194,  194,  198,  198,  278,   16,   16,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,  277,
      276,  275,  200,  274,   17,   17,  200,  200,  202,  273,
      209,  272,  202,  202,  209,  209,  211,  271,  213,  270,

      211,  211,  213,  213,  269,   17,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,  268,  267,  266,
      215,  265,   18,   18,  215,  215,  217,  264,  219,  263,
      217,  217,  219,  219,  221,  262,  223,  249,  221,  221,
      223,  223,  248,   18,   18,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,  247,  246,  245,  225,  244,
       19,   19,  225,  225,  227,  240,  229,  239,  227,  227,
      229,  229,  231,  237,  236,  234,  231,  231,  232,  230,
      228,   19,   19,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,  226,  224,  222,  220,  218,   20,   20,

      216,  214,  212,  210,  208,  206,  205,  204,  203,  201,
      199,  197,  196,  195,  193,  192,  191,  189,  188,   20,
       20,   23,   23,   23,   23,   23,   23,   23,   23,  179,
       23,  163,  160,  157,  155,  154,   23,   23,  153,  152,
      151,  150,  142,  141,  137,  136,  133,  127,  123,  119,
      116,  115,  112,  108,  103,   97,   93,   23,   23,   24,
       24,   24,   24,   24,   24,   24,   24,   89,   24,   88,
       85,   84,   80,   79,   24,   24,   71,   70,   69,   64,
       60,   57,   56,   55,   54,   51,   50,   49,   46,   44,
       41,    0,    0,    0,    0,   24,   24,   25,   25,   25,

       25,   25,   25,   25,   25,    0,   25,    0,    0,    0,
        0,    0,   25,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   25,   25,   26,   26,   26,   26,   26,
       26,   26,   26,    0,   26,    0,    0,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   26,   26,   29,   29,   29,    0,   29,   29,   29,
       29,    0,   29,    0,    0,    0,    0,    0,   29,   29,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   29,
       29,   30,   30,   30,    0,   30,   30,   30,   30,    0,
       30,    0,    0,    0,    0,    0,   30,   30,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   30,   30,   31,
       31,   31,    0,   31,   31,   31,   31,    0,   31,    0,
        0,    0,    0,    0,   31,   31,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   31,   31,   32,   32,   32,
        0,   32,   32,   32,   32,    0,   32,    0,    0,    0,

        0,    0,   32,   32,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   32,   32,   33,   33,   33,   33,   33,
       33,   33,   33,   33,   33,    0,    0,    0,    0,    0,
       33,   33,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   33,   33,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   34,    0,    0,    0,    0,    0,   34,   34,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   34,

       34,   37,   37,   37,   37,   37,   37,   37,   37,    0,
       37,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   37,   37,   38,
       38,   38,   38,   38,   38,   38,   38,    0,   38,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   38,   38,   39,   39,   39,
       39,   39,   39,   39,   39,    0,   39,    0,    0,    0,
        0,    0,   39,   39,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   39,   39,   40,   40,   40,   40,   40,
       40,   40,   40,    0,   40,    0,    0,    0,    0,    0,
       40,   40,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   40,   40,  327,  327,  327,  327,  327,  327,  328,
      328,  328,  328,  328,  328,  329,  329,  329,  329,  329,
      329,  330,  330,  330,  330,  330,  330,  331,  331,  331,
      331,  331,  331,  332,  332,  332,  332,  332,  332,  333,
      333,  333,  333,  333,  333,  334,  334,  334,  334,  334,

      334,  335,  335,  335,  335,  335,  335,  336,  336,  336,
      336,  336,  336,  337,  337,  337,  337,  337,  337,  338,
      338,  338,  338,  338,  338,  339,  339,  339,  339,  339,
      339,  340,  340,  340,  340,  340,  340,  341,  341,  341,
      341,  341,  341,  342,  342,  342,  342,  342,  342,  343,
      343,  343,  343,  343,  343,  344,  344,  344,  344,  344,
      344,  345,    0,  345,  345,  345,  345,  346,  346,  346,
      347,    0,  347,  347,  347,  347,  348,    0,  348,  348,
      348,  348,  349,    0,  349,  349,  349,  349,  350,    0,
      350,  350,  350,  350,  351,    0,  351,  351,  351,  351,

      352,    0,  352,  352,  352,  352,  353,    0,  353,  353,
      353,  353,  354,    0,  354,  354,  354,  354,  355,    0,
      355,  355,  355,  355,  356,    0,  356,  356,  356,  356,
      357,    0,  357,  358,    0,  358,  358,  358,  358,  359,
      359,  360,    0,  360,  360,  360,  360,  361,  361,  362,
        0,  362,  362,  362,  362,  363,    0,  363,  363,  363,
      363,  364,    0,  364,  364,  364,  364,  365,  365,  365,
      366,    0,  366,  366,  366,  366,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,

      326,  326,  326,  326,  326,  326,  326,  326,  326,  326,
      326,  326,  326,  326,  326
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tema.l"
#line 2 "tema.l"
    // INSERT NAME HERE
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>
    #include <iostream>
    #include <map>
    #include <string>
    #include <vector>
    
    #define GLOBAL 0
    #define AUTOMATA 1
    #define GRAMMAR 2

    using namespace std;

    int states = 0; // numarul de stari din automat
    int first_letter = 1; // imi spune daca e prima litera afisata din alfabet
    int is_final_state = 0; // imi spune daca automatul are stari finale
    char name[50]; // numele variabilei
    char initial_state[100]; // numele starii de unde incepe tranzitia
    char new_stack[1000]; // stringul care descrie stiva dupa tranzitie
    char transition_str[100000]; // stringul care descrie functia de tranzitie
    string current_transition; // string care descrie tranzitia pentru o valoare din variabila
    char variable_name[100]; // numele variabilei
    int variable_place; // locul unde e declarata varibila (global sau local in automat/gramatica)
    char variabile_values[100]; // string care contine valorile unei varibile 
    bool variable = false; // imi zice daca inputul la tranzitie e variabila sau nu
    map<string, string> global_variables; // retin variabilele globale
    map<string, string> local_variables; // retin variabilel locale
    vector<string> variable_transitions; // retin tranzitiile pentru fiecare valoare ale variabilei
#line 857 "lex.yy.c"
#line 35 "tema.l"
    // optiune sa scap de erorile de compilare pentru c++
    // starile folosite





#line 866 "lex.yy.c"

#define INITIAL 0
#define TYPE 1
#define GRAMMAR_ELEMENTS 2
#define LETTERS 3
#define PRINT_LETTERS 4
#define AUTOMATA_ELEMENTS 5
#define AUTOMATA_ALPHABET 6
#define STATES 7
#define INITIAL_STATE 8
#define FINAL_STATES 9
#define AUTOMATA_LETTERS 10
#define AUTOMATA_PRINT 11
#define TRANSITION 12
#define INPUT 13
#define STACK 14
#define NEW_STACK 15
#define END_STATE 16
#define STACK_ALPHABET 17
#define VARIABLE 18
#define VARIABLE_VALUES 19

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 50 "tema.l"


    /* Ignora comentariile simple */
#line 1106 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 327 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1177 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 53 "tema.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 "tema.l"
{}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 55 "tema.l"
{}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "tema.l"
{}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 57 "tema.l"
{}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 58 "tema.l"
{}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 59 "tema.l"
{}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 60 "tema.l"
{}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "tema.l"
{}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 62 "tema.l"
{}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "tema.l"
{}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 64 "tema.l"
{}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 65 "tema.l"
{}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 66 "tema.l"
{}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 67 "tema.l"
{}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 68 "tema.l"
{}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 69 "tema.l"
{}
	YY_BREAK
/* Ignora comentariile multi-line */
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 72 "tema.l"
{}
	YY_BREAK
case 19:
/* rule 19 can match eol */
YY_RULE_SETUP
#line 73 "tema.l"
{}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 74 "tema.l"
{}
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 75 "tema.l"
{}
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 76 "tema.l"
{}
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 77 "tema.l"
{}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 78 "tema.l"
{}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 79 "tema.l"
{}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 80 "tema.l"
{}
	YY_BREAK
case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 81 "tema.l"
{}
	YY_BREAK
case 28:
/* rule 28 can match eol */
YY_RULE_SETUP
#line 82 "tema.l"
{}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 83 "tema.l"
{}
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 84 "tema.l"
{}
	YY_BREAK
case 31:
/* rule 31 can match eol */
YY_RULE_SETUP
#line 85 "tema.l"
{}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 86 "tema.l"
{}
	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 87 "tema.l"
{}
	YY_BREAK
case 34:
/* rule 34 can match eol */
YY_RULE_SETUP
#line 88 "tema.l"
{}
	YY_BREAK
case 35:
/* rule 35 can match eol */
YY_RULE_SETUP
#line 89 "tema.l"
{}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 91 "tema.l"
{
    variable_place = GLOBAL; // retin ca e variabila globala
    BEGIN(VARIABLE); // incep sa ii caut numele
} // Gasesc declararea unei variabile globale;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 96 "tema.l"
{
    variable_place = GRAMMAR; // retin ca e variabila locala in gramatica
    BEGIN(VARIABLE); // incep sa ii caut numele
} // Gasesc declararea unei variabile in gramatica;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "tema.l"
{
    variable_place = AUTOMATA; // retin ca e variabila local in automat
    BEGIN(VARIABLE); // incep sa ii caut numele
} // Gasesc declararea unei variabile in automat;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 106 "tema.l"
{
    strcpy(variable_name, yytext); // copiez numele varibilei
    strcpy(variabile_values, "");
    BEGIN(VARIABLE_VALUES); // incep sa caut valorile
} // Iau denumirea variabilei
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 112 "tema.l"
{
    strcat(variabile_values, yytext); // am gasit o valoare, o adaug in string
} // Iau valorile variabilei
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 116 "tema.l"
{ // am gasit acolada inchisa, deci am terminat valorile
    // convertesc in string numele si valorile
    string name = string(variable_name);
    string values = string(variabile_values);
    
    // le adaug in map-ul lor corespunzator vizibilitatii 
    if (variable_place == GLOBAL) {
        global_variables[name] = values;
        BEGIN(INITIAL);    
    }
    else {
        local_variables[name] = values;
        if (variable_place == AUTOMATA) {
            BEGIN(AUTOMATA_ELEMENTS);
        } else {
            BEGIN(GRAMMAR_ELEMENTS);
        }
    }
} // Am terminat de prelucrat variabila
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 136 "tema.l"
{
    strcpy(name, yytext); // retin numele ca nu stiu ce este inca
    BEGIN(TYPE);
} // Gasesc un cuvant inseamna ca e numele gramaticii/automatului
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 141 "tema.l"
{
    printf("Numele gramaticii: %s\n", name);
    BEGIN(GRAMMAR_ELEMENTS);
} // Daca e gramatica fac lucrurile de gramatica
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 146 "tema.l"
{
    BEGIN(LETTERS);
    printf("Tipul gramaticii: -\n"); // Nu am implementat tipul gramaticii
    printf("Alfabetul gramaticii: {");    
} // Incep sa afisez alfabetul gramaticii
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 152 "tema.l"
{
    first_letter = 1;
    BEGIN(PRINT_LETTERS);
} // Incep sa iterez prin literele/simbolurile alfabetului
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 157 "tema.l"
{
    if (!first_letter) { // Daca nu e prima litera afisez spatiile si virgula
        printf(" , ");
    } else {
        first_letter = 0; // Daca nu e prima litera o afisez doar pe ea
    }
    printf("%s", yytext);
} // Am gasit o litera/cifra o afisez
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 166 "tema.l"
{ // Am gasit acolada deci am terminat cu alfabetul gramaticii
    printf("}\n");
    BEGIN(GRAMMAR_ELEMENTS);
} // Am gasit '}' se termina
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 171 "tema.l"
{
    local_variables.clear(); // Sterg variabilele locale
    printf("\n");
    BEGIN(INITIAL); // Incep sa caut urmatorul automat/gramatica
} // Am gasit ';;' se termina gramatica
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 177 "tema.l"
{
    is_final_state = 0; // Nu stiu daca are stari finale
    printf("Numele automatului: %s\n", name);
    printf("Tipul automatului: Automat cu stiva\n");
    BEGIN(AUTOMATA_ELEMENTS);
} // Daca e automat fac lucrurile de automat
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 184 "tema.l"
{
    printf("Alfabetul de intrare: {");
    BEGIN(AUTOMATA_LETTERS);
} // Cand gasesc alfabetul automatului incep sa afisez elementele acestuia
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 189 "tema.l"
{
    first_letter = 1;
    BEGIN(AUTOMATA_PRINT);
} // Incep sa iterez prin literele alfabetului
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 194 "tema.l"
{
    if (!first_letter) {
        printf(" , ");
    } else {
        first_letter = 0;
    }
    printf("%s", yytext);
} // Am gasit o litera/cifra o afisez
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 203 "tema.l"
{
    printf("}\n");
    BEGIN(AUTOMATA_ELEMENTS); // Incep sa caut restul de elemente ale automatului
} // Am gasit '}' se termina
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 208 "tema.l"
{
    BEGIN(STACK_ALPHABET);
} // Am gasit alfabetul stivei (ignor tot alfabetul stivei am pus starea sa nu faca match doare pe "alphabet")
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 212 "tema.l"
{
    BEGIN(AUTOMATA_ELEMENTS);
} // Il ignor si trec peste continut
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 216 "tema.l"
{
    states = 0;
    BEGIN(STATES); // Incep sa iterez prin stari
} // Cand gasesc starile automatului incep sa le numar
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 221 "tema.l"
{
    states++;
} // Am gasit o stare cresc contorul
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 225 "tema.l"
{
    printf("Numarul de stari: %d\n", states);
    BEGIN(AUTOMATA_ELEMENTS);
} // Cand gasesc } inseamna ca am terminat cu starile le afisez si caut restul de elemente
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 230 "tema.l"
{
    BEGIN(INITIAL_STATE);
} // Incep sa caut starea initiala
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 234 "tema.l"
{
    printf("Stare initiala: %s\n", yytext);
    BEGIN(AUTOMATA_ELEMENTS);
} // Afisez starea initiala
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 239 "tema.l"
{
    is_final_state = 1;
    states = 0; // numarul de stari finale
    printf("Starile finale: {");
    BEGIN(FINAL_STATES);
} // Incep sa caut starile finale
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 246 "tema.l"
{
    if (states > 0) { // daca e prima stare nu afisez virula si spatiu
        printf(", ");
    }
    states++;
    printf("%s", yytext);
} // Afisez starea finala
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 254 "tema.l"
{
    printf("}\n");
    BEGIN(AUTOMATA_ELEMENTS);
} // Am gasit "}" inseamna ca am afisat toate starile finale
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 259 "tema.l"
{
    strcpy(initial_state, yytext); // retin starea de unde incep tranzitia
    BEGIN(TRANSITION);
} // Am gasit o stare din care plec deci incep sa fac functia de tranzitie
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 264 "tema.l"
{
    const char delimiter_str[10] = ", ";
    current_transition = "";
    // Verific daca simbolul meu este o variabila
    if(local_variables.count(yytext) > 0) { // Verific daca e locala
        variable_transitions.clear();
        for (char c : local_variables[yytext]) {
            current_transition = "";
            current_transition += "\tm(";
            current_transition += initial_state;
            current_transition += ", ";
            current_transition += c;
            current_transition += ", ";
            variable = true;
            variable_transitions.push_back(current_transition);
        }
    } else if (global_variables.count(yytext) > 0) {
        variable_transitions.clear();
        for (char c : global_variables[yytext]) { // Verific daca e globala
            current_transition = "";            
            current_transition += "\tm(";
            current_transition += initial_state;
            current_transition += ", ";
            current_transition += c;
            current_transition += ", ";
            variable = true;
            variable_transitions.push_back(current_transition);
        }
    } else { // E simbol din alfabet
        variable = false;
        strcat(transition_str, "\tm(");
        strcat(transition_str, initial_state);
        strcat(transition_str, delimiter_str);
        strcat(transition_str, yytext);    
        strcat(transition_str, delimiter_str);
    }
    BEGIN(STACK); // Incep sa preiau elementele din stiva
} // Am gasit simbolul cu care trec in alta stare
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 303 "tema.l"
{
    if (!variable) { // Daca am avut simbol il adaug la sirul functiei de tranzitie
        strcat(transition_str, yytext);
        strcat(transition_str, ") = (");
    } else { // Daca e variabila modific sirul fiecarei valori ale variabilei
        for (int i = 0; i < variable_transitions.size(); i++) {
            variable_transitions[i] += yytext;
            variable_transitions[i] += ") = (";
        }
    }
    BEGIN(NEW_STACK); // Incep sa caut stiva dupa tranzitie
} // Am gasit stiva initiala
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 316 "tema.l"
{ // Am gasit stiva modificata
    strcpy(new_stack, "");
    strcpy(new_stack, yytext); // Ii retin continutul
    BEGIN(END_STATE); // Incep sa caut starea finala
} // Retin continutul stivei dupa ce fac tranzitia
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 322 "tema.l"
{ // Am gasit starea finala
    if (!variable) { // Daca am simbol, adaug tranzitia la functia de tranzitie
        strcat(transition_str, yytext);
        strcat(transition_str, ", ");
        strcat(transition_str, new_stack);
        strcat(transition_str, ")\n");
    } else { // Daca am avut variabila adaug tranzitiile pentru fiecare valoare a variabilei
        variable = false;
        for (int i = 0; i < variable_transitions.size(); i++) {
            variable_transitions[i] += yytext;
            variable_transitions[i] += ", ";
            variable_transitions[i] += new_stack;
            variable_transitions[i] += ")\n";     
            strcat(transition_str, variable_transitions[i].c_str());             
        }
    }
    BEGIN(TRANSITION); // Caut urmatoarea tranzitie
} // Am gasit starea noua, afisez stiva noua si starea
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 341 "tema.l"
{
    BEGIN(AUTOMATA_ELEMENTS);
} // Am gasit ")" inseamna ca se termina tranzitiile
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 345 "tema.l"
{
    local_variables.clear(); // sterg varibilele locale
    if (is_final_state == 0) {
        printf("Starile finale: {}\n");
    } // daca nu are stari finale, afisez mesaj ca nu are

    // afisez functia de tranzitie
    printf("Functia de tranzitie:\n");
    printf("%s\n",transition_str);
    
    // sterg continutul starii de tranzitie si numele starii initiale
    strcpy(transition_str, "");
    strcpy(initial_state, "");    
    BEGIN(INITIAL);
} // Am gasit ;; se termina automatul
	YY_BREAK
/* Ignor tot ce nu imi face match pe ceva ca sa nu mi le afiseze by default */
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 362 "tema.l"
{}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 363 "tema.l"
{}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 364 "tema.l"
{}
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 365 "tema.l"
{}
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 366 "tema.l"
{}
	YY_BREAK
case 76:
/* rule 76 can match eol */
YY_RULE_SETUP
#line 367 "tema.l"
{}
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 368 "tema.l"
{}
	YY_BREAK
case 78:
/* rule 78 can match eol */
YY_RULE_SETUP
#line 369 "tema.l"
{}
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 370 "tema.l"
{}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 371 "tema.l"
{}
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 372 "tema.l"
{}
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 373 "tema.l"
{}
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 374 "tema.l"
{}
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 375 "tema.l"
{}
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 376 "tema.l"
{}
	YY_BREAK
case 86:
/* rule 86 can match eol */
YY_RULE_SETUP
#line 377 "tema.l"
{}
	YY_BREAK
case 87:
/* rule 87 can match eol */
YY_RULE_SETUP
#line 378 "tema.l"
{}
	YY_BREAK
case 88:
/* rule 88 can match eol */
YY_RULE_SETUP
#line 379 "tema.l"
{}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 380 "tema.l"
ECHO;
	YY_BREAK
#line 1846 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(TYPE):
case YY_STATE_EOF(GRAMMAR_ELEMENTS):
case YY_STATE_EOF(LETTERS):
case YY_STATE_EOF(PRINT_LETTERS):
case YY_STATE_EOF(AUTOMATA_ELEMENTS):
case YY_STATE_EOF(AUTOMATA_ALPHABET):
case YY_STATE_EOF(STATES):
case YY_STATE_EOF(INITIAL_STATE):
case YY_STATE_EOF(FINAL_STATES):
case YY_STATE_EOF(AUTOMATA_LETTERS):
case YY_STATE_EOF(AUTOMATA_PRINT):
case YY_STATE_EOF(TRANSITION):
case YY_STATE_EOF(INPUT):
case YY_STATE_EOF(STACK):
case YY_STATE_EOF(NEW_STACK):
case YY_STATE_EOF(END_STATE):
case YY_STATE_EOF(STACK_ALPHABET):
case YY_STATE_EOF(VARIABLE):
case YY_STATE_EOF(VARIABLE_VALUES):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 327 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 327 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 326);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 380 "tema.l"


int main(int argc, char *argv[]){
    FILE *fp; 
    fp = fopen(argv[1],"r"); 
    yyin = fp;     
    yylex();
    return 0;
}
